name: flutter_bloc_practise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.1
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  image_picker: ^0.8.6+4
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1

flutter:
  uses-material-design: true
