name: flutter_bloc_practise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bloc: ^8.1.1
  bloc_test: ^9.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_bloc: ^8.1.2

flutter:
  uses-material-design: true
